import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  sectionTitle1: {
    fontWeight: 'bold',
  },
  sectionTitle2: {
    position: 'absolute',
    left: 31,
    top: 350,
    fontWeight: 'bold',
  },
  slowbutton: {
    position: 'absolute',
    width: 293,
    height: 73,
    left: 31,
    top: 459,
  },
  fastbutton: {
    position: 'absolute',
    width: 293,
    height: 73,
    left: 121,
    top: 459,
  },
  repeatbutton: {
    position: 'absolute',
    width: 293,
    height: 73,
    left: 221,
    top: 459,
  },
  confusedbutton: {
    position: 'absolute',
    width: 293,
    height: 73,
    left: 301,
    top: 459,
  },

  logo: {
    position: 'absolute',
    top: 355,
    left: 338,
  },
  slowlogo: {
    position: 'absolute',
    height: 50,
    width: 50,
    top: -60,
    left: 7,
  },
  fastlogo: {
    position: 'absolute',
    height: 60,
    width: 60,
    top: -63,
    left: -3,
  },
  repeatlogo: {
    position: 'absolute',
    height: 48,
    width: 48,
    top: -57,
    left: -2,
  },
  confuselogo: {
    position: 'absolute',
  },
  homebutton: {
    position: 'absolute',
    width: 293,
    height: 73,
    left: 41,
    top: 620,
  },
  homelogo: {
    position: 'absolute',
    top: -55,
    left: -7,
  },
  studentbutton: {
    position: 'absolute',
    width: 293,
    height: 73,
    left: 171,
    top: 620,
  },
  teacherbutton: {
    position: 'absolute',
    width: 293,
    height: 73,
    left: 306,
    top: 620,
  },
  studentlogo: {
    position: 'absolute',
    top: -55,
    left: -1,
  },
  teacherlogo: {
    position: 'absolute',
    top: -55,
    left: -1,
  },
  slowagree: {
    position: 'absolute',
    width: 72,
    height: 21,
    left: 81,
    top: -3,
    backgroundColor: '#70AE60',
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: '#000000',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.5,
    shadowRadius: 5,
    elevation: 5,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 10,
  },
  fastagree: {
    position: 'absolute',
    width: 72,
    height: 21,
    left: 81,
    top: 0,
    backgroundColor: '#70AE60',
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: '#000000',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.5,
    shadowRadius: 5,
    elevation: 5,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 10,
  },
  repeatagree: {
    position: 'absolute',
    width: 72,
    height: 21,
    left: 141,
    top: 0,
    backgroundColor: '#70AE60',
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: '#000000',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.5,
    shadowRadius: 5,
    elevation: 5,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 10,
  },
  confusedagree: {
    position: 'absolute',
    width: 72,
    height: 21,
    left: 81,
    top: 0,
    backgroundColor: '#70AE60',
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: '#000000',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.5,
    shadowRadius: 5,
    elevation: 5,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 10,
  },
  // container1: {
  //   position: 'absolute',
  //   width: 100,
  //   height: 120,
  //   // left: 21,
  //   // top: 100,
  //   backgroundColor: '#03a5fc',
  //   borderRadius: 12,
  // },

  // container2: {
  //   position: 'absolute',
  //   width: 100,
  //   height: 120,
  //   // left: 150,
  //   // top: 100,
  //   backgroundColor: '#03a5fc',
  //   borderRadius: 12,
  // },
});
